/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Adminui;

import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.dao.LoginInfoDAO;
import model.dao.TestInfoDao;
import model.dao.TestScheduleDao;
import model.to.LoginInfoTo;
import model.to.TestInfoTo;
import model.to.TestScheduleTo;

/**
 *
 * @author POOJA PURI
 */
public class AddTestSchedule extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddTestSchedule
     */
    private String username;

    public AddTestSchedule(String fusername) {
        this();
        this.username = fusername;
        java.sql.Date dt = new java.sql.Date(new java.util.Date().getTime());
        cdpdatepanel.setStartdate(dt);
        long time = 60L * 60 * 24 * 1000;
        time = time * 50 + dt.getTime();
        try {
            cdpdatepanel.setEnddate(new java.sql.Date(time));
        } catch (InvalidDateRangeException ex) {
        }
    }

    public AddTestSchedule() {
        initComponents();
        jcbtestid.removeAllItems();
        jcbtestid.addItem("Select TestID");
        List<TestInfoTo> test = new TestInfoDao().getAllRecord();
        if (test != null && test.size() > 0) {
            for (TestInfoTo tit : test) {
                jcbtestid.addItem(tit);
            }
        }
        //jcbfusername.removeAllItems();
        //jcbfusername.addItem("Select FUserName");
        /* List<LoginInfoTo> login = new LoginInfoDAO().getAllRecord();
        if (login != null && login.size() > 0) {
            for (LoginInfoTo lit : login) {
                jcbtestid.addItem(lit);
            }
        }*/
        jcbsusername.removeAllItems();
        jcbsusername.addItem("Select SUserName");
        List<LoginInfoTo> logins = new LoginInfoDAO().getOnlyStudent();
        if (logins != null && logins.size() > 0) {
            for (LoginInfoTo lit : logins) {
                jcbsusername.addItem(lit);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbtestid = new javax.swing.JComboBox<>();
        jcbsusername = new javax.swing.JComboBox<>();
        btnproceed = new javax.swing.JButton();
        cdpdatepanel = new Adminui.RangeDatePanel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("ES::TEST SCHEDULE");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/ex.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Choose A Test ID");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Choose A Student");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Test Date");

        jcbtestid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbsusername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnproceed.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        btnproceed.setForeground(new java.awt.Color(0, 51, 51));
        btnproceed.setText("PROCEED");
        btnproceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbtestid, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbsusername, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnproceed, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdpdatepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbtestid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbsusername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(cdpdatepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(btnproceed)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnproceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproceedActionPerformed
        String message = " ";
        boolean allvalid = true;
        if (jcbtestid.getSelectedIndex() == 0) {
            allvalid = false;
            message += "Please Choose Any Test ID \n";
        }
        /*if (jcbfusername.getSelectedIndex() == 0) {
            allvalid = false;
            message += "Please Choose Any Option \n";
        }*/
        if (jcbsusername.getSelectedIndex() == 0) {
            allvalid = false;
            message += "Please Choose Any Option \n";
        }
        if (cdpdatepanel.getSelectedDate() == null) {
            allvalid = false;
            message += "Please Choose Any Start Date \n";
        }
        if (allvalid) {
            TestScheduleTo tsit = new TestScheduleTo();
            TestInfoTo tit = (TestInfoTo) jcbtestid.getSelectedItem();

            tsit.setTestID(tit.getTestID());
            //LoginInfoTo lit=(LoginInfoTo)jcbfusername.getSelectedItem();
            LoginInfoTo Lit = (LoginInfoTo) jcbsusername.getSelectedItem();
            tsit.setSUserName(Lit.getUserName());
            tsit.setFUserName(username);
            tsit.setTestDate(cdpdatepanel.getSelectedDate());
            TestScheduleDao action = new TestScheduleDao();
            if (action.insertRecord(tsit)) {
                message += "New Record Is Added In The System";
                JInternalFrame[] frames = getDesktopPane().getAllFrames();
                if (frames != null) {

                    for (JInternalFrame jif : frames) {
                        if (jif instanceof ViewTestSchedule) {
                            ViewTestSchedule vts = (ViewTestSchedule) jif;
                            vts.bindtableTestSchedule();
                            break;
                        }
                    }
                }
                
            } else {
                message += action.getErrormessage();
                
            }

    }//GEN-LAST:event_btnproceedActionPerformed
        //JOptionPane.showMessageDialog(this, message, "Error Message From System", JOptionPane.ERROR_MESSAGE);
        JOptionPane.showMessageDialog(this, message);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproceed;
    private Adminui.RangeDatePanel cdpdatepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<Object> jcbsusername;
    private javax.swing.JComboBox<Object> jcbtestid;
    // End of variables declaration//GEN-END:variables
}
