/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Adminui;

import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import model.dao.DataConnection;

/**
 *
 * @author POOJA PURI
 */
public class AdminMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainScreen
     */
    public AdminMainScreen() {
        try{
            ImageIcon icon=new ImageIcon(getClass().getResource("/Adminui/ex.png"));
            setIconImage(icon.getImage());
        }catch(Exception ex){
            
        }
        initComponents();
        setSize(1000, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmiAddSubject = new javax.swing.JMenuItem();
        jmiViewSubject = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiAddSection = new javax.swing.JMenuItem();
        jmiViewSection = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiAddexam = new javax.swing.JMenuItem();
        jmiViewExam = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiAddQuestion = new javax.swing.JMenuItem();
        jmiViewQuestion = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmiAddSechedule = new javax.swing.JMenuItem();
        jmiViewSchedule = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        deskPane.setBackground(new java.awt.Color(255, 255, 255));
        deskPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        deskPane.setForeground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout deskPaneLayout = new javax.swing.GroupLayout(deskPane);
        deskPane.setLayout(deskPaneLayout);
        deskPaneLayout.setHorizontalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        deskPaneLayout.setVerticalGroup(
            deskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        getContentPane().add(deskPane, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setMargin(new java.awt.Insets(2, 2, 2, 2));

        jMenu3.setText("Subject ");

        jmiAddSubject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiAddSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/addd.png"))); // NOI18N
        jmiAddSubject.setText("Add Subject");
        jmiAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddSubjectActionPerformed(evt);
            }
        });
        jMenu3.add(jmiAddSubject);

        jmiViewSubject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiViewSubject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/vieww.png"))); // NOI18N
        jmiViewSubject.setText("View Subject ");
        jmiViewSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewSubjectActionPerformed(evt);
            }
        });
        jMenu3.add(jmiViewSubject);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Section");

        jmiAddSection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK));
        jmiAddSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/addd.png"))); // NOI18N
        jmiAddSection.setText("Add Section");
        jmiAddSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddSectionActionPerformed(evt);
            }
        });
        jMenu4.add(jmiAddSection);

        jmiViewSection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK));
        jmiViewSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/vieww.png"))); // NOI18N
        jmiViewSection.setText("View Section ");
        jmiViewSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewSectionActionPerformed(evt);
            }
        });
        jMenu4.add(jmiViewSection);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exam Detail");

        jmiAddexam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/addd.png"))); // NOI18N
        jmiAddexam.setText("Add Exam");
        jmiAddexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddexamActionPerformed(evt);
            }
        });
        jMenu5.add(jmiAddexam);

        jmiViewExam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/vieww.png"))); // NOI18N
        jmiViewExam.setText("View Exam Detail");
        jmiViewExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewExamActionPerformed(evt);
            }
        });
        jMenu5.add(jmiViewExam);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Questions");

        jmiAddQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/addd.png"))); // NOI18N
        jmiAddQuestion.setText("Add New Question");
        jmiAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddQuestionActionPerformed(evt);
            }
        });
        jMenu6.add(jmiAddQuestion);

        jmiViewQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/vieww.png"))); // NOI18N
        jmiViewQuestion.setText("View Question");
        jmiViewQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewQuestionActionPerformed(evt);
            }
        });
        jMenu6.add(jmiViewQuestion);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Exam Schedule");

        jmiAddSechedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/addd.png"))); // NOI18N
        jmiAddSechedule.setText("Add Exam Schedule");
        jmiAddSechedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddSecheduleActionPerformed(evt);
            }
        });
        jMenu7.add(jmiAddSechedule);

        jmiViewSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/vieww.png"))); // NOI18N
        jmiViewSchedule.setText("View Schedule");
        jmiViewSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewScheduleActionPerformed(evt);
            }
        });
        jMenu7.add(jmiViewSchedule);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Result");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DataConnection.CloseConnection();
    }//GEN-LAST:event_formWindowClosing

    private void jmiAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddSubjectActionPerformed
       ShowScreen(new AddSubjectInfo());
    }//GEN-LAST:event_jmiAddSubjectActionPerformed

    private void ShowScreen(JInternalFrame jif){
        jif.setVisible(true);
        deskPane.add(jif);
        try{
            jif.setSelected(true);
        }catch(PropertyVetoException ex){
            
        }
    }
    
    private void jmiAddSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddSectionActionPerformed
        ShowScreen(new AddSectionInfo());
    }//GEN-LAST:event_jmiAddSectionActionPerformed

    private void jmiAddexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddexamActionPerformed
        ShowScreen(new AddTestInfo());
    }//GEN-LAST:event_jmiAddexamActionPerformed

    private void jmiAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddQuestionActionPerformed
        ShowScreen(new AddTestQuestion());
    }//GEN-LAST:event_jmiAddQuestionActionPerformed

    private void jmiAddSecheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddSecheduleActionPerformed
        ShowScreen(new AddTestSchedule());
    }//GEN-LAST:event_jmiAddSecheduleActionPerformed

    private void jmiViewSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewSubjectActionPerformed
        ShowScreen(new ViewSubjectInfo());
    }//GEN-LAST:event_jmiViewSubjectActionPerformed

    private void jmiViewSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewSectionActionPerformed
        ShowScreen(new ViewSectionInfo());
    }//GEN-LAST:event_jmiViewSectionActionPerformed

    private void jmiViewExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewExamActionPerformed
       ShowScreen(new ViewExamDetail());
    }//GEN-LAST:event_jmiViewExamActionPerformed

    private void jmiViewQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewQuestionActionPerformed
        ShowScreen(new ViewTestQuestion());
    }//GEN-LAST:event_jmiViewQuestionActionPerformed

    private void jmiViewScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewScheduleActionPerformed
        ShowScreen(new ViewTestSchedule());
    }//GEN-LAST:event_jmiViewScheduleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
          //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAddQuestion;
    private javax.swing.JMenuItem jmiAddSechedule;
    private javax.swing.JMenuItem jmiAddSection;
    private javax.swing.JMenuItem jmiAddSubject;
    private javax.swing.JMenuItem jmiAddexam;
    private javax.swing.JMenuItem jmiViewExam;
    private javax.swing.JMenuItem jmiViewQuestion;
    private javax.swing.JMenuItem jmiViewSchedule;
    private javax.swing.JMenuItem jmiViewSection;
    private javax.swing.JMenuItem jmiViewSubject;
    // End of variables declaration//GEN-END:variables
}
