/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Adminui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.dao.TestScheduleDao;
import model.to.TestScheduleTo;

/**
 *
 * @author POOJA PURI
 */
public class ViewTestSchedule extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewTestSchedule
     */
        List<TestScheduleTo> schedule;
        private JPopupMenu popupmenu;
        int row;
    public ViewTestSchedule() {
        initComponents();
        bindtableTestSchedule();
        row=-1;
        popupmenu=new JPopupMenu();
        JMenuItem jmiDelete=new JMenuItem("Delete This Record");
  //      JMenuItem jmiEdit=new JMenuItem("Edit This Record");  
        jmiDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
        popupmenu.add(jmiDelete);
//        popupmenu.add(jmiEdit);
    }
    private void deleteRecord(){
        if(row!=-1&&schedule!=null&&row<schedule.size()){
            int result=JOptionPane.showConfirmDialog(this, "Are you Sure You Want To Delete This Information ?","Message From The System",JOptionPane.YES_NO_OPTION);
            if(result==JOptionPane.YES_OPTION){
               String message="";
               TestScheduleTo tst=schedule.get(row);
               if(tst!=null){
                   TestScheduleDao action=new TestScheduleDao();
                   if(action.deleteRecord(String.valueOf(tst.getScheduleId()))){
                       message="Selected Test Schedule Information Is Deleted";
                       bindtableTestSchedule();
                   }else{
                       message=action.getErrormessage();
                   }
                   JOptionPane.showMessageDialog(this, message);
               }
            }
        }
        row=-1;
    }
    public void bindtableTestSchedule(){
    schedule=new TestScheduleDao().getAllRecord();
    String[] colnames={"Schedule ID","FUser Name","Suser Name","TestDate","TestID"};
    Object[][] records=null;
    if(schedule!=null&& schedule.size()>0){
        records=new Object[schedule.size()][colnames.length];
        int i=0;
        for(TestScheduleTo tsit: schedule){
            records[i]=new Object[]{tsit.getScheduleId(),tsit.getFUserName(),tsit.getSUserName(),tsit.getTestDate(),tsit.getTestID()};
            i++;
        }
    }else{
        records=new Object[1][colnames.length];
        records[0]=new Object[]{"No record","No record","No record","No record","No record"};
    }
    DefaultTableModel dtm=new DefaultTableModel(records, colnames){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
       };
    tableviewschedule.getTableHeader().setReorderingAllowed(false);
    tableviewschedule.setAutoCreateRowSorter(true);
    tableviewschedule.setModel(dtm);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableviewschedule = new javax.swing.JTable();
        btnrefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("ES: VIEW TEST SCHEDULE");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Adminui/ex.png"))); // NOI18N

        tableviewschedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableviewschedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableviewscheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableviewschedule);

        btnrefresh.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        bindtableTestSchedule();

    }//GEN-LAST:event_btnrefreshActionPerformed

    private void tableviewscheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableviewscheduleMouseClicked
        if(evt.getButton()==MouseEvent.BUTTON3){
            int rowpoint=tableviewschedule.rowAtPoint(evt.getPoint());
            tableviewschedule.getSelectionModel().setSelectionInterval(rowpoint, rowpoint);
            popupmenu.show(tableviewschedule,evt.getX(),evt.getY());
            row=tableviewschedule.getSelectedRow();
        }
    }//GEN-LAST:event_tableviewscheduleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableviewschedule;
    // End of variables declaration//GEN-END:variables
}
