/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam.suite;

import Userui.StudentPanel;
import Adminui.AddSectionInfo;
import Adminui.AddSubjectInfo;
import Adminui.AddTestInfo;
import Adminui.AddTestQuestion;
import Adminui.AddTestSchedule;
import Adminui.AdminMainScreen;
import Operations.Validations;
import Userui.AdminScreen;
import Userui.FacultyScreen;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.dao.LoginInfoDAO;
import model.to.LoginInfoTo;

/**
 *
 * @author POOJA PURI
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource("/Userui/images.jpg"));
            setIconImage(icon.getImage());
        } catch (Exception ex) {

        }
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel1 = new exam.suite.BackPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ES::Login");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter User Name:");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter User Password:");

        btnLogin.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        btnLogin.setText("SIGN IN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backPanel1Layout = new javax.swing.GroupLayout(backPanel1);
        backPanel1.setLayout(backPanel1Layout);
        backPanel1Layout.setHorizontalGroup(
            backPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(backPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(backPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(backPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        backPanel1Layout.setVerticalGroup(
            backPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(backPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(backPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnLogin)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String UserName = jtfUserName.getText();
        String Password = new String(jpfPassword.getPassword());
        String message = "";
        if (Validations.isEmpty(UserName) || Validations.isEmpty(Password)) {
            message = "Provide All Values";
        } else {
            LoginInfoTo lit = new LoginInfoDAO().getRecord(UserName);
            if (lit == null) {
                message += "INVALID USERNAME";
            } else if (lit.getPassword().equals(Password)) {
                if (lit.getRoleName() != null) {
                    if (lit.getRoleName().equalsIgnoreCase("admin")) {
                        AdminScreen as = new AdminScreen();
                        as.setVisible(true);
                        message = "Welcome Admin For The First  Time";
                        if (lit.getLastLogin() != null) {
                            message = "Welcome Admin Your Last Visit On:" + lit.getLastLogin();
                        }
                        new LoginInfoDAO().updateRecord(UserName);

                        dispose();
                    } else if (lit.getRoleName().equalsIgnoreCase("faculty")) {
                        FacultyScreen fsc = new FacultyScreen();
                        fsc.setUsername(UserName);
                        fsc.setVisible(true);
                        message = "Welcome Faculty Member For The First  Time";
                        if (lit.getLastLogin() != null) {
                            message = "Welcome Faculty Member Your Last Visit On:" + lit.getLastLogin();
                        }
                        new LoginInfoDAO().updateRecord(UserName);
                        dispose();
                    } else if (lit.getRoleName().equalsIgnoreCase("student")) {
                        StudentPanel spnl = new StudentPanel(UserName);
                        spnl.setVisible(true);
                        message = "Welcome Student For The First  Time";
                        if (lit.getLastLogin() != null) {
                            message = "Welcome "+UserName+" Your Last Visit was On:" + lit.getLastLogin();
                        }
                        new LoginInfoDAO().updateRecord(UserName);
                        dispose();
                    }
                } else {
                    message = "You Are Not Authorized User To Acess This Application";
                }
            } else {
                message = "INVALID USERNAME AND PASSWORD";
            }

        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private exam.suite.BackPanel backPanel1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
